[package]
name = "rigel"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.14.0"

[dependencies]
starknet = "2.14.0"

[lib]
path = "src/lib.cairo"

[cairo]
enable-gas = true

[dev-dependencies]
snforge_std = "0.56.0"
